# Site
name: "Damiano Giusti"
title: "Damiano Giusti's Blog"
description: >
  Hi everybody, Damiano's here! 
  Software Engineer @ MOLO17 focused on Android apps development. 
  Welcome to my blog, a place where I share some pills from my every day experience about mobile apps development 
  and software engineering.
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
baseurl: ''
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: null
include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-twitter-plugin
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"